name: Build Anon Proxy

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.build.runner }}
    strategy:
      fail-fast: false
      matrix:
        build:

          # Ubuntu x64
          - runner: ubuntu-latest
            os: linux
            arch: amd64
            lib: so.4

          # MacOS Intel
          - runner: macos-13
            os: macos
            arch: amd64
            lib: dylib

          # MacOS Apple Silicon
          - runner: macos-14
            os: macos
            arch: arm64
            lib: dylib

    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: ./configure

      - name: Build Anon Proxy
        run: make

      - name: Run Anon Proxy
        run: ./anon-proxy -v

      - name: Run tests
        run: ./src/proxychains -f dist/proxychains.conf on

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anon-proxy-${{ matrix.build.os }}-${{ matrix.build.arch }}
          path: |
            anon-proxy
            libanon-proxy.${{ matrix.build.lib }}

  release-github:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Copy release artifacts
        run: |
          mkdir -p release-artifacts/
          chmod +x artifacts/anon-*/*
          zip -j release-artifacts/anon-proxy-linux-amd64.zip artifacts/anon-proxy-linux-amd64/*
          zip -j release-artifacts/anon-proxy-macos-amd64.zip artifacts/anon-proxy-macos-amd64/*
          zip -j release-artifacts/anon-proxy-macos-arm64.zip artifacts/anon-proxy-macos-arm64/*
          ls -la -R release-artifacts/
      - name: Publish release artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release-artifacts/anon-*.zip"
