name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: ./configure

      - name: Build Proxychains
        run: make

      - name: Run Proxychains
        run: ./anon-proxy -v

      - name: Run tests
        run: ./src/proxychains -f dist/proxychains.conf on

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: ./configure

      - name: Build Proxychains
        run: make

      - name: Run Proxychains
        run: ./anon-proxy -v

      - name: Run tests
        run: ./src/proxychains -f dist/proxychains.conf on
