name: Build Anon Proxy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: ./configure

      - name: Build Anon Proxy
        run: make

      - name: Run Anon Proxy
        run: ./anon-proxy -v

      - name: Run tests
        run: ./src/proxychains -f dist/proxychains.conf on

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anon-proxy-linux
          path: anon-proxy

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: ./configure

      - name: Build Anon Proxy
        run: make

      - name: Run Anon Proxy
        run: ./anon-proxy -v

      - name: Run tests
        run: ./src/proxychains -f dist/proxychains.conf on

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anon-proxy-macos
          path: anon-proxy
